/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package day2

import kotlin.test.*
import kotlin.test.Test

val data =
    """
  A Y
  B X
  C Z
    """.trimIndent()

class AppTest {
    @Test fun scoreIsCorrect() {
        val subject = App()

        val rounds = subject.parse(data)
        assertEquals(rounds.size, 3)
        val score = subject.calculateTotalScore(rounds)

        assertEquals(score, 12)
    }
}
