/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package day1

import day1.Elf

class App {
  fun parse(data: String): List<Elf> {
    val arr: ArrayList<Elf> = ArrayList<Elf>()

    val lines = data.lines().map { it.trim() }
    var currentCalories = 0
    for(line in lines) {
      if (line.isNullOrBlank()) {
        if (currentCalories > 0) {
          arr.add(Elf(arr.size + 1, currentCalories))
          currentCalories = 0
        }
      } else {
        currentCalories += line.toInt()
      }
    }

    return arr
  }
}

fun main() {
  
}
